# Accent Dictionaries:

# STANDARD MUSICAL CONTEXT: ba bum ba ba bum ba ba bum
accent_dict = { ' ba ':' ^ '
               ,' bum ':' / '

# PERSONAL PRONOUNS: assume personal pronouns are NOT stressed
               ,' i ':' ^ '
               ,' me ':' ^ '
               ,' you ':' ^ '
               ,' he ':' ^ '
               ,' she ':' ^ '
               ,' him ':' ^ '
               ,' her ':' ^ '
               ,' it ':' ^ '
               ,' they ':' ^ '
               ,' them ':' ^ '
               ,' us ':' ^ '
               ,' we ':' ^ '

# POSSESSIVE PRONOUNS: ???
               ,' your ':' ^ '
               ,' yours ':' ^ '
               ,' my ':' ^ '
               ,' mine ':' ^ '
               ,' his ':' ^ '
               ,' her ':' ^ '
               ,' hers ':' ^ '
               ,' our ':' ^ '
               ,' ours ':' ^ '
               ,' their ':' ^ '
               ,' theirs ':' ^ '

# ARTICLES: assume articles are NOT stressed
               ,' a ':' ^ '
               ,' an ':' ^ '
               ,' the ':' ^ '

# CONJUNCTIONS: assume conjunctions are NOT stressed
               ,' and ':' ^ '
               ,' or ':' ^ '
               ,' but ':' ^ '

# PREPOSITIONS: assume prepositions are NOT stressed
               ,' to ':' ^ '
               ,' in ':' ^ '
               ,' for ':' ^ '
               ,' of ':' ^ '
               ,' on ':' ^ '
               ,' at ':' ^ '
               ,' since ':' ^ '
               ,' ago ':' ^ '
               ,' before ':' ^ '
               ,' past ':' ^ '
               ,' until ':' ^ '
               ,' till ':' ^ '
               ,' til ':' ^ '
               ,' by ':' ^ '
               ,' with ':' ^ '

# Other: ???
               ,' like ':' ^ '
               ,' as ':' ^ '
               ,' just ':' ^ '
               ,' from ':' ^ '
               ,' so ':' ^ '
               ,' still ':' ^ '
               ,' yet ':' ^ '

# Questions: ???
               ,' what ':' / '
               ,' which ':' / '
               ,' why ':' / '
               ,' when ':' / '
               ,' where ':' / '
               ,' who ':' / '
               ,' whos ':' / '
               ,' whose ':' / '
               ,' whom ':' / '
               ,' how ':' / '

# Area: ???
               ,' here ':' / '
               ,' there ':' / '

# assume single syllable nouns, verbs, adjectives, and adverbs are stressed
               ,' oh ':' ^ '
               ,' aye ':' ^ '
               ,' ay ':' ^ '
               ,' cuz ':' ^ '
               ,' yeah ':' ^ '
               ,' yes ':' ^ '
               ,' no ':' ^ '
               # Outside:
               ,' sky ':' / '
               ,' skies ':' / '
               ,' sun ':' / '
               ,' suns ':' / '
               ,' out ':' / '
               ,' tree ':' / '
               ,' trees ':' / '
               # Time:
               ,' day ':' / '
               ,' days ':' / '
               ,' night ':' / '
               ,' nights ':' / '
               ,' long ':' / '
               ,' last ':' / '
               ,' lasts ':' / '
               ,' now ':' / '
               # Direction:
               ,' road ':' / '
               ,' roads ':' / '
               ,' way ':' / '
               ,' ways ':' / '
               ,' street ':' / '
               ,' streets ':' / '
               ,' up ':' / '
               ,' down ':' / '
               # Home:
               ,' home ':' / '
               ,' homes ':' / '
               ,' room ':' / '
               ,' rooms ':' / '
               ,' bed ':' / '
               ,' beds ':' / '
               # Family:
               ,' kin ':' / '
               # Location:
               ,' place ':' / '
               # Amounts:
               ,' all ':' / '
               # Boosters / Deboosters:
               ,' good ':' / '
               ,' goods ':' / '
               ,' worse ':' / '
               # Want:
               ,' need ':' / '
               ,' needs ':' / '
               # Color:
               ,' red ':' / '
               ,' blue ':' / '
               ,' green ':' / '
               ,' black ':' / '
               ,' white ':' / '
               ,' grey ':' / '
               ,' gray ':' / '
               ,' light ':' / '
               # Body: 
               ,' butt ':' / '
               ,' butts ':' / '
               ,' mouth ':' / '
               ,' mouths ':' / '
               ,' lip ':' / '
               ,' lips ':' / '
               ,' arm ':' / '
               ,' arms ':' / '
               ,' foot ':' / '
               ,' feet ':' / '
               ,' head ':' / '
               ,' heads ':' / '
               ,' hair ':' / '
               ,' hairs ':' / '
               ,' leg ':' / '
               ,' legs ':' / '
               # Other / Uncategorized: 
               ,' own ':' / '
               ,' side ':' / '
               ,' sides ':' / '
               ,' fruit ':' / '
               ,' fruits ':' / '
               ,' right ':' / '
               ,' rights ':' / '
               ,' worth ':' / '
               # Religion:
               ,' god ':' / '
               ,' gods ':' / '
               ,' church ':' / '
               ,' soul ':' / '
               ,' souls ':' / '
               ,' hell ':' / '
               # Being:
               ,' is ':' / '
               ,' its ':' / '
               ,' am ':' / '
               ,' im ':' / '
               ,' youre ':' / '
               ,' are ':' / '
               ,' were ':' / '
               ,' be ':' / '
               # Action:
               ,' do ':' / '
               ,' doing ':' /^ '
               ,' done ':' / '
               ,' dont ':' / '
               ,' make ':' / '
               ,' making ':' /^ '
               ,' made ':' / '
               ,' wont ':' / '
               ,' can ':' / '
               ,' cant ':' / '
               ,' could ':' / '
               ,' would ':' / '
               ,' wont ':' / '
               ,' burn ':' / '
               ,' burning ':' /^ '
               ,' burned ':' / '
               ,' know ':' / '
               ,' knows ':' / '
               ,' knowing ':' /^ '
               ,' knew ':' / '
               ,' work ':' / '
               ,' working ':' /^ '
               ,' worked ':' / '
               ,' give ':' / '
               ,' giving ':' /^ '
               ,' gave ':' / '
               ,' get ':' / '
               ,' gets ':' / '
               ,' getting ':' /^ '
               ,' got ':' / '
               ,' take ':' / '
               ,' taking ':' /^ '
               ,' took ':' / '
               ,' talk ':' / '
               ,' talking ':' /^ '
               ,' talked ':' / '
               ,' speak ':' / '
               ,' speaking ':' /^ '
               ,' spoke ':' / '
               ,' have ':' / '
               ,' having ':' /^ '
               ,' had ':' / '
               ,' love ':' / '
               ,' loving ':' /^ '
               ,' loved ':' / '
               ,' die ':' / '
               ,' dying ':' /^ '
               ,' died ':' / '
               ,' dead ':' / '
               ,' drink ':' / '
               ,' drinking ':' /^ '
               ,' drunk ':' / '
               ,' eat ':' / '
               ,' eating ':' /^ '
               ,' ate ':' / '
               ,' lick ':' / '
               ,' licking ':' /^ '
               ,' licked ':' / '
               ,' swing ':' / '
               ,' swinging ':' /^ '
               ,' swung ':' / '
               ,' need ':' / '
               ,' needing ':' /^ '
               ,' needed ':' /? '
               ,' want ':' / '
               ,' wanting ':' /^ '
               ,' wanted ':' /? '
               ,' go ':' / '
               ,' goes ':' / '
               ,' going ':' /^ '
               ,' went ':' / '
               ,' gone ':' / '
               ,' leave ':' / '
               ,' leaving ':' /^ '
               ,' left ':' / '
               ,' come ':' / '
               ,' coming ':' /^ '
               ,' came ':' / '
               ,' feel ':' / '
               ,' feeling ':' /^ '
               ,' felt ':' / '
               ,' deal ':' / '
               ,' dealing ':' /^ '
               ,' delt ':' / '
               ,' steal ':' / '
               ,' stealing ':' /^ '
               ,' stolen ':' /^ '
               ,' stole ':' / '
               ,' find ':' / '
               ,' finds ':' / '
               ,' finding ':' /^ '
               ,' findings ':' /^ '
               ,' found ':' / '
               ,' teach ':' / '
               ,' teaching ':' /^ '
               ,' taught ':' / '
               ,' shine ':' / '
               ,' shining ':' /^ '
               ,' shined ':' / '
               ,' hide ':' / '
               ,' hiding ':' /^ '
               ,' hidden ':' /^ '


###################################################
###################################################
## RISING METERS:

# IAMBIC METER:
               ,' today ':' ^/ '
               ,' about ':' ^/ '
               ,' alone ':' ^/ '
               ,' apart ':' ^/ '

# ANAPESTIC METER:
               ,' understand ':' ^^/ '
               ,' disagree ':' ^^/ '

###################################################
###################################################
## FALLING METERS:

# TROCHAIC METER:
               ,' pretty ':' /^ '
               ,' sunny ':' /^ '
               ,' eden ':' /^ '
               ,' witches ':' /^ '
               ,' devil ':' /^ '
               ,' devils ':' /^ '
               ,' baby ':' /^ '
               ,' babys ':' /^ '
               ,' babies ':' /^ '
               ,' sorry ':' /^ '
               ,' always ':' /^ '
               ,' maybe ':' /^ '
               ,' naked ':' /^ '
               ,' outside ':' /^ '
               ,' perfect ':' /^ '
               ,' comfort ':' /^ '
               ,' party ':' /^ ' 
               ,' parties ':' /^ ' 
               ,' liquor ':' /^ '
               ,' liquors ':' /^ '
               ,' circuit ':' /^ '
               ,' circuits ':' /^ '
               ,' something ':' /^ '
               ,' body ':' /^ '
               ,' bodys ':' /^ '
               ,' bodies ':' /^ '
               ,' mother ':' /^ '
               ,' father ':' /^ '
               ,' brother ':' /^ '
               ,' sister ':' /^ '
               ,' mothers ':' /^ '
               ,' fathers ':' /^ '
               ,' brothers ':' /^ '
               ,' sisters ':' /^ '
               ,' adam ':' /^ '
               ,' lucky ':' /^ '
               ,' never ':' /^ '

# DACTYLIC METER:
               ,' elephant ':' /^^ '
               ,' syllable ':' /^^ '
               ,' everything ':' /^^ '
               ,' evergreen ':' /^^ '
               ,' evergreens ':' /^^ '

# ??? METER /^/:
               ,' demeanor ':' /^/ '

###################################################
###################################################
## FALLING METERS: can be used to 'breakup' rhythm in lyrics or insert an irregularity into a pattern

# SPONDAIC METER:
               ,' toothache ':' // '
               ,' handshake ':' // '

# PYRRHIC METER:
               ,' to a ':' ^ ^ '
               ,' in the ':' ^ ^ '
               }
