# Lyric List:
lyric_list = [
 '  ba  bum  ba  ba  bum  ba  ba  bum  '
########################
### Other Lyrics, Self Written:
,'  as  long  as  it  lasts  '
,'  today  is  going  to  be  a  good  day  '
,'  apart  from  my  own  demeanor  '
,'  i  just  dont  understand  '
,'  im  sorry  but  i  disagree  '
,'  you  are  so  pretty  '
,'  it  is  sunny  outside  '
,'  the  elephant  in  the  room  '
,'  which  syllable  would  you  like  '
,'  i  have  a  toothache  '
,'  give  me  a  handshake  '
,'  what  what  in  the  butt  '
,'  i  am  going  to  a  party  '
########################
### Punk as Fuck Lyrics / American Analog Set:
,'  i  am  on  your  side  '
,'  and  were  always  right  '
,'  its  perfect  '
,'  but  worth  it  '
,'  youre  on  my  side  '
,'  and  were  always  right  '
,'  its  a  circuit  '
,'  but  it  gets  worse  yeah  '
,'  i  am  your  side  '
,'  and  were  always  right  '
,'  its  a  circuit  '
,'  but  it  gets  worse  yeah  '
,'  cuz  you  need  me  to  die  in  the  comfort  of  my  own  home  '
,'  of  my  own  home  '
,'  of  my  own  home  '
########################
### Naked and Red Lyrics / Colour Revolt:
,'  god  is  swinging  from  the  liquor  tree  '
,'  licking  everything  he  finds  '
,'  god  knows  all  about  you  and  me  '
,'  lucky  i  got  something  to  hide  '
,'  all  alone  in  the  evergreens  '
,'  babys  got  a  soul  to  steal  '
,'  i  know  you  and  you  know  me  '
,'  maybe  we  can  make  a  deal  '
,'  there  goes  adam  with  the  devils  head  '
,'  his  bodys  all  naked  and  red  '
,'  were  all  naked  now  in  our  heads  '
,'  but  i  know  whos  made  my  bed  '
,'  still  i  feel  sorry  for  the  devils  kin  '
,'  his  mother  never  taught  him  no  good  '
,'  im  still  swinging  from  the  liquor  tree  '
,'  and  eden  is  a  hell  of  a  place  '
,'  eden  '
,'  eden  '
,'  eden  is  a  hell  of  a  place  '
,'  eden  '
,'  eden  '
,'  eden  is  a  hell  of  a  place  '
,'  talk  talk  talk  talk  your  devils  down  '
,'  sun  sun  sun  sun  its  coming  out  '
,'  and  burn  burn  burn  your  witches  out  '
,'  and  work  work  work  til  the  day  is  out  '
,'  talk  talk  talk  talk  your  devils  down  '
,'  sun  sun  sun  sun  its  coming  out  '
,'  burn  burn  burn  burn  your  witches  out  '
,'  oh  talk  talk  your  devils  down  '
,'  sun  sun  its  coming  out  '
,'  burn  burn  your  witches  out  '
,'  work  work  the  day  is  out  '
,'  talk  talk  talk  talk  talk  your  devils  down  '
,'  sun  sun  sun  its  coming  out  '
,'  burn  burn  burn  your  witches  out '
]